// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZpNDOsQNSL0WhoaKlRd45ilPZapWc_7c',
    appId: '1:531056872253:web:c19b4fdaa035e8c8759354',
    messagingSenderId: '531056872253',
    projectId: 'project-akhir-20125',
    authDomain: 'project-akhir-20125.firebaseapp.com',
    storageBucket: 'project-akhir-20125.appspot.com',
    measurementId: 'G-DT45EV2LYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0TX7UUv8iLi-bF36RtEl36MQRbPW6wWQ',
    appId: '1:531056872253:android:9ca14218601c353b759354',
    messagingSenderId: '531056872253',
    projectId: 'project-akhir-20125',
    storageBucket: 'project-akhir-20125.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVhWUUEQjFD1uX-Do0THSyFk1NWjTSCE4',
    appId: '1:531056872253:ios:260dfb646b5bf029759354',
    messagingSenderId: '531056872253',
    projectId: 'project-akhir-20125',
    storageBucket: 'project-akhir-20125.appspot.com',
    androidClientId: '531056872253-snp4pbac6t3hv58ejuqvsjtg5iiovlfh.apps.googleusercontent.com',
    iosClientId: '531056872253-2v9gpls3tludbkppd0tc6bq1j7irovlr.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVhWUUEQjFD1uX-Do0THSyFk1NWjTSCE4',
    appId: '1:531056872253:ios:260dfb646b5bf029759354',
    messagingSenderId: '531056872253',
    projectId: 'project-akhir-20125',
    storageBucket: 'project-akhir-20125.appspot.com',
    androidClientId: '531056872253-snp4pbac6t3hv58ejuqvsjtg5iiovlfh.apps.googleusercontent.com',
    iosClientId: '531056872253-2v9gpls3tludbkppd0tc6bq1j7irovlr.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject2023',
  );
}
